import { StoryObj } from '@storybook/react';
import { Flex } from '../../flex/index.ts';
import { DataTable } from '../DataTable.tsx';
import { INVOICES } from './INVOICES.ts';
import { Configuration } from '../../configuration/index.ts';
import { Text } from '../../text/index.ts';

const DATA = [
  {
    id: 1,
    name: 'Хронометр Переходов',
    description:
      'Механический прибор, который фиксирует моменты резких жизненных перемен. Стрелка двигается только во время значимых решений.',
    inventoryNumber: 102938,
    value: 450000,
    currencyCode: 'RUB',
    secretKey: '****92AF',
    foundDate: '2024-02-12',
    month: 2,
    year: 2024,
    verified: true,
    tags: ['время', 'механизмы'],
    sourceLink: 'https://museum.example.com/item/1',
    color: '#C0A368',
    custom: { energyLevel: 0.92 },
  },
  {
    id: 2,
    name: 'Сфера Тихого Звука',
    description:
      'Матовая сфера, которая подавляет любой звук в радиусе метра. Используется учёными для экспериментов с абсолютной тишиной.',
    inventoryNumber: 849201,
    value: 3200,
    currencyCode: 'USD',
    secretKey: '****QW12',
    foundDate: '2019-08-01',
    month: 8,
    year: 2019,
    verified: false,
    tags: ['акустика', 'тишина'],
    sourceLink: 'https://museum.example.com/item/2',
    color: '#7A7FBA',
    custom: { energyLevel: 1 },
  },
  {
    id: 3,
    name: 'Фолиант Сновидений',
    description:
      'Книга, страницы которой меняются каждую ночь. Содержимое зависит от снов владельца.',
    inventoryNumber: 119284,
    value: 12000,
    currencyCode: 'EUR',
    secretKey: '****AB91',
    foundDate: '2020-11-17',
    month: 11,
    year: 2020,
    verified: true,
    tags: ['книги', 'сны'],
    sourceLink: 'https://museum.example.com/item/3',
    color: '#5F4C6B',
    custom: { energyLevel: 243 },
  },
  {
    id: 4,
    name: 'Гармонический Кристалл',
    description:
      'Издаёт тихий звук, частота которого повышается рядом с эмоционально нестабильными людьми.',
    inventoryNumber: 903421,
    value: 56000,
    currencyCode: 'CHF',
    secretKey: '****CCB2',
    foundDate: '2018-05-09',
    month: 5,
    year: 2018,
    verified: true,
    tags: ['кристаллы', 'звук'],
    sourceLink: 'https://museum.example.com/item/4',
    color: '#88D0F5',
    custom: { energyLevel: 227.5 },
  },
  {
    id: 5,
    name: 'Латунная Маска Правды',
    description: 'Человек, надевший маску, временно теряет способность лгать.',
    inventoryNumber: 774220,
    value: 230000,
    currencyCode: 'GBP',
    secretKey: '****TT12',
    foundDate: '2017-12-30',
    month: 12,
    year: 2017,
    verified: false,
    tags: ['маски', 'легенды'],
    sourceLink: 'https://museum.example.com/item/5',
    color: '#D4AF37',
    custom: { energyLevel: 3 },
  },
  {
    id: 6,
    name: 'Компас Затерянных Троп',
    description:
      'Стрелка компаса указывает направления, которых не существует на карте, будто бы предлагая новые пути.',
    inventoryNumber: 540912,
    value: 80000,
    currencyCode: 'RUB',
    secretKey: '****F88C',
    foundDate: '2023-10-02',
    month: 10,
    year: 2023,
    verified: true,
    tags: ['навигация', 'аномалии'],
    sourceLink: 'https://museum.example.com/item/6',
    color: '#2F4F4F',
    custom: { energyLevel: 42 },
  },
  {
    id: 7,
    name: 'Акварель Погоды',
    description:
      'Картина меняет цвета в зависимости от погодных условий в месте, где находится наблюдатель.',
    inventoryNumber: 111204,
    value: 670000,
    currencyCode: 'JPY',
    secretKey: '****T1F4',
    foundDate: '2021-02-22',
    month: 2,
    year: 2021,
    verified: false,
    tags: ['искусство', 'погода'],
    sourceLink: 'https://museum.example.com/item/7',
    color: '#ADD8E6',
    custom: { energyLevel: 'rain' },
  },
  {
    id: 8,
    name: 'Кварцевый Будильник Судьбы',
    description:
      'Звенит только в те дни, когда человеку предстоит судьбоносное событие.',
    inventoryNumber: 332801,
    value: 15900,
    currencyCode: 'USD',
    secretKey: '****0A7B',
    foundDate: '2022-07-19',
    month: 7,
    year: 2022,
    verified: true,
    tags: ['время', 'предсказания'],
    sourceLink: 'https://museum.example.com/item/8',
    color: '#E8D5C4',
    custom: { energyLevel: 7 },
  },
  {
    id: 9,
    name: 'Керамическая Чаша Эха',
    description: 'Произнесённая в неё фраза повторяется спустя ровно сутки.',
    inventoryNumber: 882301,
    value: 9900,
    currencyCode: 'AUD',
    secretKey: '****B1AA',
    foundDate: '2016-04-11',
    month: 4,
    year: 2016,
    verified: false,
    tags: ['звук', 'керамика'],
    sourceLink: 'https://museum.example.com/item/9',
    color: '#F0EAD6',
    custom: { energyLevel: 24 },
  },
  {
    id: 10,
    name: 'Фонарь Забытой Дороги',
    description:
      'Яркость света увеличивается, если владелец идёт в правильном направлении по жизни.',
    inventoryNumber: 200441,
    value: 72300,
    currencyCode: 'CAD',
    secretKey: '****99EF',
    foundDate: '2021-09-03',
    month: 9,
    year: 2021,
    verified: true,
    tags: ['свет', 'символизм'],
    sourceLink: 'https://museum.example.com/item/10',
    color: '#FFFACD',
    custom: { energyLevel: 0.74 },
  },
  {
    id: 11,
    name: 'Перо Пересказчика',
    description:
      'Перо, которое записывает историю не так, как она была, а как её чувствовал участник событий.',
    inventoryNumber: 552230,
    value: 21000,
    currencyCode: 'EUR',
    secretKey: '****S0F0',
    foundDate: '2018-01-15',
    month: 1,
    year: 2018,
    verified: true,
    tags: ['письменность', 'эмоции'],
    sourceLink: 'https://museum.example.com/item/11',
    color: '#FFDAB9',
    custom: { energyLevel: 0.68 },
  },
  {
    id: 12,
    name: 'Ключ Отсутствующих Дверей',
    description:
      'Металлический ключ с насечками, не подходящий ни к одному известному замку.',
    inventoryNumber: 912883,
    value: 3800,
    currencyCode: 'USD',
    secretKey: '****9X0M',
    foundDate: '2020-06-01',
    month: 6,
    year: 2020,
    verified: false,
    tags: ['металл', 'загадки'],
    sourceLink: 'https://museum.example.com/item/12',
    color: '#B0C4DE',
    custom: { energyLevel: 17 },
  },
  {
    id: 13,
    name: 'Лента Воспоминаний',
    description:
      'Ткань, которая становится теплее при прикосновении к человеку, вспоминающему важное событие.',
    inventoryNumber: 484920,
    value: 12500,
    currencyCode: 'GBP',
    secretKey: '****WW22',
    foundDate: '2019-10-07',
    month: 10,
    year: 2019,
    verified: true,
    tags: ['ткань', 'память'],
    sourceLink: 'https://museum.example.com/item/13',
    color: '#FFC1CC',
    custom: { energyLevel: 0.38 },
  },
  {
    id: 14,
    name: 'Зеркало Несказанного',
    description: 'Отражает не внешний вид, а невысказанные мысли.',
    inventoryNumber: 672381,
    value: 570000,
    currencyCode: 'CNY',
    secretKey: '****XY2L',
    foundDate: '2015-03-19',
    month: 3,
    year: 2015,
    verified: false,
    tags: ['зеркала', 'психология'],
    sourceLink: 'https://museum.example.com/item/14',
    color: '#E6E6FA',
    custom: { energyLevel: 0.83 },
  },
  {
    id: 15,
    name: 'Шахматы Без Короля',
    description:
      'Набор фигур, в котором отсутствуют короли. Игроки сами решают, кто является главной фигурой.',
    inventoryNumber: 390221,
    value: 33000,
    currencyCode: 'RUB',
    secretKey: '****K1L9',
    foundDate: '2022-11-25',
    month: 11,
    year: 2022,
    verified: true,
    tags: ['игры', 'философия'],
    sourceLink: 'https://museum.example.com/item/15',
    color: '#8B4513',
    custom: { energyLevel: 30 },
  },
  {
    id: 16,
    name: 'Песочные Часы Отступления',
    description:
      'Песок течёт назад, если человек хочет отменить принятое решение.',
    inventoryNumber: 941102,
    value: 41000,
    currencyCode: 'USD',
    secretKey: '****OP00',
    foundDate: '2020-01-09',
    month: 1,
    year: 2020,
    verified: true,
    tags: ['время', 'решения'],
    sourceLink: 'https://museum.example.com/item/16',
    color: '#D2B48C',
    custom: { energyLevel: true },
  },
  {
    id: 17,
    name: 'Лунный Камертон',
    description: 'Издаёт чистый звук только в полнолуние.',
    inventoryNumber: 552011,
    value: 99000,
    currencyCode: 'EUR',
    secretKey: '****LK19',
    foundDate: '2017-07-07',
    month: 7,
    year: 2017,
    verified: false,
    tags: ['звук', 'луна'],
    sourceLink: 'https://museum.example.com/item/17',
    color: '#AFEEEE',
    custom: { energyLevel: 'full moon' },
  },
  {
    id: 18,
    name: 'Свиток Ускользающих Истин',
    description: 'Надписи исчезают, если человек сомневается в увиденном.',
    inventoryNumber: 118822,
    value: 245000,
    currencyCode: 'USD',
    secretKey: '****M8N2',
    foundDate: '2018-09-14',
    month: 9,
    year: 2018,
    verified: true,
    tags: ['письменность', 'знание'],
    sourceLink: 'https://museum.example.com/item/18',
    color: '#FAFAD2',
    custom: { energyLevel: 0.41 },
  },
  {
    id: 19,
    name: 'Музыкальная Коробка Памяти',
    description:
      'Проигрывает мелодию, которую владелец слышал в самый счастливый момент жизни.',
    inventoryNumber: 701202,
    value: 87000,
    currencyCode: 'JPY',
    secretKey: '****P0Q9',
    foundDate: '2023-03-04',
    month: 3,
    year: 2023,
    verified: true,
    tags: ['музыка', 'память'],
    sourceLink: 'https://museum.example.com/item/19',
    color: '#FFEFD5',
    custom: { energyLevel: 12 },
  },
  {
    id: 20,
    name: 'Очки Верного Выбора',
    description:
      'Через линзы вещи, ведущие к удаче, подсвечиваются мягким золотым оттенком.',
    inventoryNumber: 190284,
    value: 14500,
    currencyCode: 'USD',
    secretKey: '****WQ2Z',
    foundDate: '2021-08-29',
    month: 8,
    year: 2021,
    verified: false,
    tags: ['зрение', 'удача'],
    sourceLink: 'https://museum.example.com/item/20',
    color: '#FFD700',
    custom: { energyLevel: 0.52 },
  },
  {
    id: 21,
    name: 'Скрижаль Невозможных Слов',
    description:
      'Содержит слова, которые невозможно произнести человеческим голосом.',
    inventoryNumber: 502391,
    value: 330000,
    currencyCode: 'CNY',
    secretKey: '****L1X1',
    foundDate: '2016-02-23',
    month: 2,
    year: 2016,
    verified: true,
    tags: ['язык', 'мистика'],
    sourceLink: 'https://museum.example.com/item/21',
    color: '#F5F5DC',
    custom: { energyLevel: 87 },
  },
  {
    id: 22,
    name: 'Медальон Сонной Дороги',
    description: 'Указывает человеку путь, который ему снится чаще всего.',
    inventoryNumber: 661012,
    value: 56000,
    currencyCode: 'EUR',
    secretKey: '****DO8K',
    foundDate: '2022-04-11',
    month: 4,
    year: 2022,
    verified: true,
    tags: ['сны', 'пути'],
    sourceLink: 'https://museum.example.com/item/22',
    color: '#AFEEEE',
    custom: { energyLevel: 0.71 },
  },
  {
    id: 23,
    name: 'Карта Перемещённых Мест',
    description:
      'Объекты на карте иногда меняют местоположение, будто отражая сны картографа.',
    inventoryNumber: 800311,
    value: 99000,
    currencyCode: 'GBP',
    secretKey: '****J1S9',
    foundDate: '2021-12-09',
    month: 12,
    year: 2021,
    verified: false,
    tags: ['карты', 'изменчивость'],
    sourceLink: 'https://museum.example.com/item/23',
    color: '#E0FFFF',
    custom: { energyLevel: 5 },
  },
  {
    id: 24,
    name: 'Кристаллическая Антенна Мысли',
    description:
      'Излучает слабые колебания, совпадающие с эмоциональным состоянием владельца.',
    inventoryNumber: 390112,
    value: 185000,
    currencyCode: 'USD',
    secretKey: '****T7C1',
    foundDate: '2019-03-14',
    month: 3,
    year: 2019,
    verified: true,
    tags: ['кристаллы', 'эмоции'],
    sourceLink: 'https://museum.example.com/item/24',
    color: '#87CEEB',
    custom: { energyLevel: 0.56 },
  },
  {
    id: 25,
    name: 'Часы Забытых Мелочей',
    description:
      'Останавливаются каждый раз, когда человек теряет что-то незначительное, но важное.',
    inventoryNumber: 771204,
    value: 47000,
    currencyCode: 'EUR',
    secretKey: '****U2P0',
    foundDate: '2023-05-06',
    month: 5,
    year: 2023,
    verified: true,
    tags: ['время', 'потери'],
    sourceLink: 'https://museum.example.com/item/25',
    color: '#F5DEB3',
    custom: { energyLevel: 14 },
  },
];

export const StoryWithDifferentRenderers: StoryObj<typeof Flex> = {
  name: 'Story With Different Renderers',
  render: () => {
    return (
      <Configuration locale={{ dateFormat: 'DD MMM YYYY' }}>
        <DataTable
          data={DATA}
          columns={[
            { accessor: 'id', label: 'ID', type: 'number', width: 50 },
            {
              accessor: 'name',
              label: 'Name',
              type: 'string',
              filterable: true,
            },
            {
              accessor: 'description',
              label: 'Description',
              type: 'text',
              filterable: true,
            },
            {
              accessor: 'inventoryNumber',
              label: 'Inventory Number',
              type: 'number',
              filterable: true,
            },
            {
              accessor: 'value',
              label: 'Value',
              type: 'currency',
              options: { currencyAccessor: 'currencyCode' },
              filterable: true,
            },
            {
              accessor: 'verified',
              label: 'Verified',
              type: 'boolean',
              width: 80,
              filterable: true,
            },
            {
              accessor: 'foundDate',
              label: 'Full Found Date',
              type: 'date',
              options: { level: 'day' },
              filterable: true,
            },
            {
              accessor: 'foundDate',
              label: 'Found Month',
              type: 'date',
              options: { level: 'month' },
              filterable: true,
            },
            {
              accessor: 'foundDate',
              label: 'Found Year',
              type: 'date',
              options: { level: 'year' },
              filterable: true,
            },
            {
              accessor: 'secretKey',
              label: 'Secret Key',
              type: 'password',
              filterable: true,
              width: 100,
            },
            {
              accessor: 'tags',
              label: 'Tags',
              type: 'select',
              filterable: true,
            },
            {
              accessor: 'sourceLink',
              label: 'Source Link',
              type: 'link',
              options: {
                hrefTransformer: (value) => String(value),
                textTransformer: () => 'See in action',
              },
              filterable: true,
            },
            {
              accessor: 'color',
              label: 'Color',
              type: 'color',
              filterable: true,
            },
            {
              accessor: 'custom',
              label: 'Code',
              type: 'custom',
              options: {
                renderReadMode: ({ value }) => (
                  <Text code>{JSON.stringify(value)}</Text>
                ),
              },
            },
          ]}
        />
      </Configuration>
    );
  },
};
