/**
 * Component logo assets, published under the `altrone-ui/logos` subpath so they
 * are only pulled into a consumer bundle when explicitly imported.
 *
 * For each logo there are two exports: `<Name>` — a React component rendering an
 * inline `<svg>` (accepts standard SVG props), and `<name>Url` — the resolved
 * asset URL (for `<img src>` / CSS `background-image`).
 */
import applicationUrl from './application.svg';
import Application from './application.svg?react';
import screenUrl from './screen.svg';
import Screen from './screen.svg?react';
import configurationUrl from './configuration.svg';
import Configuration from './configuration.svg?react';
import textUrl from './text.svg';
import Text from './text.svg?react';
import boxUrl from './box.svg';
import Box from './box.svg?react';
import altrone4Url from './altrone4.svg';
import Altrone4 from './altrone4.svg?react';
import gridUrl from './grid.svg';
import Grid from './grid.svg?react';
import flexUrl from './flex.svg';
import Flex from './flex.svg?react';
import drawerUrl from './drawer.svg';
import Drawer from './drawer.svg?react';
import popoverUrl from './popover.svg';
import Popover from './popover.svg?react';
import dropdownUrl from './dropdown.svg';
import Dropdown from './dropdown.svg?react';
import tooltipUrl from './tooltip.svg';
import Tooltip from './tooltip.svg?react';
import modalUrl from './modal.svg';
import Modal from './modal.svg?react';
import scrollableUrl from './scrollable.svg';
import Scrollable from './scrollable.svg?react';
import collapsedListUrl from './collapsed-list.svg';
import CollapsedList from './collapsed-list.svg?react';
import formUrl from './form.svg';
import Form from './form.svg?react';
import splitterUrl from './splitter.svg';
import Splitter from './splitter.svg?react';
import spoilerUrl from './spoiler.svg';
import Spoiler from './spoiler.svg?react';
import toolbarUrl from './toolbar.svg';
import Toolbar from './toolbar.svg?react';
import buttonUrl from './button.svg';
import Button from './button.svg?react';
import textInputUrl from './text-input.svg';
import TextInput from './text-input.svg?react';
import passwordInputUrl from './password-input.svg';
import PasswordInput from './password-input.svg?react';
import numberInputUrl from './number-input.svg';
import NumberInput from './number-input.svg?react';
import autocompleteInputUrl from './autocomplete-input.svg';
import AutocompleteInput from './autocomplete-input.svg?react';
import searchUrl from './search.svg';
import Search from './search.svg?react';
import textareaUrl from './textarea.svg';
import Textarea from './textarea.svg?react';
import selectUrl from './select.svg';
import Select from './select.svg?react';
import checkboxUrl from './checkbox.svg';
import Checkbox from './checkbox.svg?react';
import switcherUrl from './switcher.svg';
import Switcher from './switcher.svg?react';
import radioUrl from './radio.svg';
import Radio from './radio.svg?react';
import datePickerUrl from './date-picker.svg';
import DatePicker from './date-picker.svg?react';
import colorPickerUrl from './color-picker.svg';
import ColorPicker from './color-picker.svg?react';
import filePickerUrl from './file-picker.svg';
import FilePicker from './file-picker.svg?react';
import rangeUrl from './range.svg';
import Range from './range.svg?react';
import calendarUrl from './calendar.svg';
import Calendar from './calendar.svg?react';
import dataTableUrl from './data-table.svg';
import DataTable from './data-table.svg?react';
import dialogUrl from './dialog.svg';
import Dialog from './dialog.svg?react';
import messageUrl from './message.svg';
import Message from './message.svg?react';
import progressUrl from './progress.svg';
import Progress from './progress.svg?react';
import tagsUrl from './tags.svg';
import Tags from './tags.svg?react';
import notificationsUrl from './notifications.svg';
import Notifications from './notifications.svg?react';
import navigationListUrl from './navigation-list.svg';
import NavigationList from './navigation-list.svg?react';
import bottomNavigationUrl from './bottom-navigation.svg';
import BottomNavigation from './bottom-navigation.svg?react';
import sideNavigationUrl from './side-navigation.svg';
import SideNavigation from './side-navigation.svg?react';
import tabsUrl from './tabs.svg';
import Tabs from './tabs.svg?react';
import breadcrumbsUrl from './breadcrumbs.svg';
import Breadcrumbs from './breadcrumbs.svg?react';
import paginationUrl from './pagination.svg';
import Pagination from './pagination.svg?react';
import avatarUrl from './avatar.svg';
import Avatar from './avatar.svg?react';
import dividerUrl from './divider.svg';
import Divider from './divider.svg?react';
import resultUrl from './result.svg';
import Result from './result.svg?react';
import closeButtonUrl from './close-button.svg';
import CloseButton from './close-button.svg?react';
import labelUrl from './label.svg';
import Label from './label.svg?react';
import loadingUrl from './loading.svg';
import Loading from './loading.svg?react';
import skeletonUrl from './skeleton.svg';
import Skeleton from './skeleton.svg?react';

export { Application, applicationUrl };
export { Screen, screenUrl };
export { Configuration, configurationUrl };
export { Text, textUrl };
export { Box, boxUrl };
export { Altrone4, altrone4Url };
export { Grid, gridUrl };
export { Flex, flexUrl };
export { Drawer, drawerUrl };
export { Popover, popoverUrl };
export { Dropdown, dropdownUrl };
export { Tooltip, tooltipUrl };
export { Modal, modalUrl };
export { Scrollable, scrollableUrl };
export { CollapsedList, collapsedListUrl };
export { Form, formUrl };
export { Splitter, splitterUrl };
export { Spoiler, spoilerUrl };
export { Toolbar, toolbarUrl };
export { Button, buttonUrl };
export { TextInput, textInputUrl };
export { PasswordInput, passwordInputUrl };
export { NumberInput, numberInputUrl };
export { AutocompleteInput, autocompleteInputUrl };
export { Search, searchUrl };
export { Textarea, textareaUrl };
export { Select, selectUrl };
export { Checkbox, checkboxUrl };
export { Switcher, switcherUrl };
export { Radio, radioUrl };
export { DatePicker, datePickerUrl };
export { ColorPicker, colorPickerUrl };
export { FilePicker, filePickerUrl };
export { Range, rangeUrl };
export { Calendar, calendarUrl };
export { DataTable, dataTableUrl };
export { Dialog, dialogUrl };
export { Message, messageUrl };
export { Progress, progressUrl };
export { Tags, tagsUrl };
export { Notifications, notificationsUrl };
export { NavigationList, navigationListUrl };
export { BottomNavigation, bottomNavigationUrl };
export { SideNavigation, sideNavigationUrl };
export { Tabs, tabsUrl };
export { Breadcrumbs, breadcrumbsUrl };
export { Pagination, paginationUrl };
export { Avatar, avatarUrl };
export { Divider, dividerUrl };
export { Result, resultUrl };
export { CloseButton, closeButtonUrl };
export { Label, labelUrl };
export { Loading, loadingUrl };
export { Skeleton, skeletonUrl };
